User Account (Sidebar & Addresses & OrdersList)
hlxsites/boilerplate-commerce-dropins pull request #108
Opened 2024-08-28 15:35 UTC by Ferri0

TODO

Test URLs:
- Before: https://main--boilerplate-commerce-dropins--hlxsites.hlx.live/
- After: https://account-sidebar--boilerplate-commerce-dropins--hlxsites.hlx.live/

2024-09-09 18:39 UTC, fnhipster requested changes

2024-09-09 18:39 UTC, fnhipster commented on scripts/configs.js
> +  if (configParam === 'commerce-core-endpoint') return 'https://mcstaging.aemshop.net/graphql'
Is this hardcoded while developing?

2024-09-09 18:39 UTC, fnhipster commented on blocks/commerce-search-order/commerce-search-order.js
> +  events.on('order/data', async (orderData) => {
Shouldn't this and the logic of `checIsOrderBelongsToCustomer` be implemented in the Container itself?

2024-09-09 18:39 UTC, fnhipster commented on blocks/commerce-account-sidebar/commerce-account-sidebar.js
> +  accountRenderer.render(Icon, { source: iconSource, size: 32 })(iconEl);
Let's use the render function from the Components instead. 

```js
import { Icon, provider as uiProvider } from '@dropins/tools/components.js';

uiProvider.render(Icon, { ... })(iconElem);
```

2024-09-09 18:39 UTC, fnhipster commented on blocks/commerce-order-data-initializer/commerce-order-data-initializer.js
Can you fix GitHub warnings? It makes it difficult to review. Can I get some background on this Block "Commerce Order Data Initializer"? Not sure if this should be a "Block" given that it seems to just initialize code. Perhaps this could be moved to `scripts/dropins.js` with a conditions that checks if the page matches the template?

2024-09-10 12:19 UTC, Ferri0 commented on blocks/commerce-order-data-initializer/commerce-order-data-initializer.js
Lint warnings have been fixed, sorry about that. For some reason, ESLint stopped working correctly in the boilerplate environment in PHPStorm—I'll look into that.

As for your suggestion, I had considered it as well, but wanted to hear another opinion. It makes sense to me, so I'll move the logic to `scripts/dropins.js`

2024-09-10 12:21 UTC, Ferri0 commented on scripts/configs.js
> +  if (configParam === 'commerce-core-endpoint') return 'https://mcstaging.aemshop.net/graphql'
Yes, I accidentally committed this code. It's been removed ✅

2024-09-10 12:22 UTC, Ferri0 commented on blocks/commerce-search-order/commerce-search-order.js
> +  events.on('order/data', async (orderData) => {
Probably you right, I will look into moving this redirects logic to component and make URLs configurable via route callbacks. Thank you for the suggestion!

2024-09-17 11:05 UTC, Ferri0 commented
PR moved to https://github.com/hlxsites/aem-boilerplate-commerce

New PR - https://github.com/hlxsites/aem-boilerplate-commerce/pull/101

2024-09-17 11:05 UTC, closed without merging