[IN PROGRESS] Integrate auth drop-in
hlxsites/boilerplate-commerce-dropins pull request #26
Opened 2024-04-10 15:18 UTC by Ferri0

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--boilerplate-commerce-dropins--hlxsites.hlx.live/customer/login
- After: https://auth-dropin--boilerplate-commerce-dropins--hlxsites.hlx.live/customer/login

2024-04-10 16:22 UTC, sirugh commented on blocks/commerce-account/commerce-account.js
> +  block.innerHTML = '';
We may want to include some copy in this page that indicates it's mocked/placeholder/WIP.

2024-04-10 16:25 UTC, Ferri0 commented on blocks/commerce-account/commerce-account.js
> +  block.innerHTML = '';
Sure, will do. Still in progress, will finalise everything in next few days 👍

2024-04-15 08:10 UTC, herzog31 commented on blocks/commerce-account/helpers/convertDateFormat.js
> +/* eslint-disable consistent-return */
You can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#:~:text=%22numeric%22%2C-,month%3A%20%22long%22%2C,-day%3A%20%22numeric to get the full localized name of a month.

2024-04-15 08:10 UTC, herzog31 commented on blocks/commerce-create-account/commerce-create-account.js
> +import { render as authRenderer } from '../../scripts/__dropins__/storefront-auth/render.js';
For the render imports of all blocks you can use the package import syntax `@dropins/storefront-auth/render.js`.

2024-04-15 12:22 UTC, Ferri0 commented on blocks/commerce-account/api/customer/fragments/customerAddressFragment.js
> +const customerAddressFragment = `
Thank you for the suggestion! Please, notice that whole `blocks/commerce-account` block is just a temporally demo page which eventually will be replaced by My Account drop-in, we didn't focus much on implementation details, just copied solution from our sandbox for demo purposes (appropriate comment added to `blocks/commerce-account/commerce-account.js`).

I've refactored implementation and removed all fragments and needless GraphQL queries.

2024-04-15 12:23 UTC, Ferri0 commented on blocks/commerce-account/api/shared/GqlClient.js
> +/* eslint-disable class-methods-use-this */
Thank you for the suggestion! Please, notice that whole `blocks/commerce-account` block is just a temporally demo page which eventually will be replaced by My Account drop-in, we didn't focus much on implementation details, just copied solution from our sandbox for demo purposes (appropriate comment added to `blocks/commerce-account/commerce-account.js`).

I've refactored implementation and removed the `GqlClient` at all, to omit possible confusion.

2024-04-15 12:23 UTC, Ferri0 commented on blocks/commerce-account/helpers/convertDateFormat.js
> +/* eslint-disable consistent-return */
Good point, I've refactored the `convertDateFromat.js` function. Thank you!

2024-04-15 12:24 UTC, Ferri0 commented on blocks/commerce-create-account/commerce-create-account.js
> +import { render as authRenderer } from '../../scripts/__dropins__/storefront-auth/render.js';
Good point, thank you! I've refactored import syntax in all blocks 👍

2024-04-15 12:26 UTC, Ferri0 commented on blocks/commerce-account/commerce-account.js
> +  block.innerHTML = '';
I've included the commented copy in this page with clear `TODO` comment.

Additionally, I've added `TODO` comment in the commerce-account block clearly specifying that this is temporally component only for demo and testing purposes.

2024-04-15 12:44 UTC, Ferri0 commented
Hi @sirugh,
I need some assistance with 403 error which appears in `https://mcprod.aemshop.net/graphq` / `https://mcstaging.aemshop.net/graphq` environments for the following GraphQL query - https://developer.adobe.com/commerce/webapi/graphql/schema/attributes/queries/attributes-form/. You can check the error here - https://auth-dropin--boilerplate-commerce-dropins--hlxsites.hlx.live/customer/create

Request in local environment (success):
<img width="1723" alt="Screenshot 2024-04-15 at 13 56 27" src="https://github.com/hlxsites/boilerplate-commerce-dropins/assets/67440994/1eef0403-91c6-445b-a054-a1d5111234d9">

Errors in production environment:
<img width="1723" alt="Screenshot 2024-04-15 at 13 56 50" src="https://github.com/hlxsites/boilerplate-commerce-dropins/assets/67440994/95b19811-69ce-4d26-a01c-341c6f0ebf81">
<img width="1723" alt="Screenshot 2024-04-15 at 13 56 55" src="https://github.com/hlxsites/boilerplate-commerce-dropins/assets/67440994/b530443d-19b5-4f62-b62c-158fd65f2612">

I've tried to perform request via Insomnia/Postman to `https://mcprod.aemshop.net/graphq`, endpoint seems to be fully functional:
<img width="1291" alt="Screenshot 2024-04-15 at 14 31 10" src="https://github.com/hlxsites/boilerplate-commerce-dropins/assets/67440994/6beb5bb7-7285-4b54-a778-0de7f1c202a7">

Other requests performed by auth drop-in also not causing any errors. I'm assuming that there might be some issue on BE/server side.

2024-04-15 14:23 UTC, sirugh commented
Interesting. IIRC the ACAO headers for the graphql API were set to `*` for both staging and prod. And that tracks with what  where ACAO is `*` in the response of the OPTIONS request.

@blakebauman @dpatil-magento, can y'all confirm this?

My guess is we have either:

a) an issue in the DNS (either setting in cors allowed headers module settings OR at fastly)
b) an issue in Adobe Commerce that handles this specific query.

@Ferri0 please confirm, it seems that you had an issue ONLY with this `attributesForm` query but not other queries?

2024-04-15 14:25 UTC, Ferri0 commented
@sirugh yes, currently I've faced this issue only with `attributesForm` query. Other auth-related queries and mutations which I have tested so far working fine.

2024-04-15 15:17 UTC, Ferri0 commented
**UPD**
The issue was caused by the excessive length of the URL. We resolved it by switching from GET to POST or by trimming the query used in the GET request. This solution has addressed the problem for this specific instance. However, it's important to remain aware of this limitation, as longer queries could still exceed the limit, even with minification.
<img width="1556" alt="Screenshot 2024-04-15 at 16 59 47" src="https://github.com/hlxsites/boilerplate-commerce-dropins/assets/67440994/0a386fd4-a56a-4fcc-bd62-893a13909404">
cc @sirugh

2024-04-24 10:22 UTC, Ferri0 commented on blocks/commerce-login/commerce-login.js
> +        messageText: 'Your account has been successfully created.',
Good point, fixed ✅

2024-05-14 16:55 UTC, sirugh requested changes

2024-05-14 16:55 UTC, sirugh commented on package-lock.json
> +      "resolved": "https://artifactory-uw2.adobeitc.com/artifactory/api/npm/npm-storefront-sdk-release/@dropins/storefront-auth/-/storefront-auth-0.0.1-alpha2.tgz",
We should not have artifactory refs in the boilerplate lockfile. Please re-generate this and ensure no artifactory refs are included.

2024-05-29 09:49 UTC, herzog31 approved these changes
LGTM

2024-05-29 19:38 UTC, sirugh approved these changes

2024-05-29 19:38 UTC, sirugh commented on scripts/configs.js
> +};
Something like the following would have identical behavior but be more readable :)

```suggestion
export const getCookie = (cookieName) => {
  const cookies = document.cookie.split(';');
  for (const cookie of cookies) {
    const [name, value] = cookie.trim().split('=');
    if (name === cookieName) {
      return decodeURIComponent(value);
    }
  }
  return undefined;
};
```

2024-05-30 15:33 UTC, Ferri0 commented on scripts/configs.js
> +};
Make sense 👍 

I've did it slightly differently since ESLint don't like for loop 🙈 However, RegExp eliminated 👍 

> ESLint: iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.(no-restricted-syntax)

2024-05-30 15:35 UTC, Ferri0 commented
I'm merging PR with auth drop-in integration into boilerplate ✅ 

All key auth flow and integration with cart drop-in is in place, integration with checkout drop-in pending, and will be delivered as a separate PR.

2024-05-30 15:35 UTC, merged