Logged-in User Checkout: Basic Flow
hlxsites/boilerplate-commerce-dropins pull request #49
Opened 2024-05-17 13:14 UTC by emipallares

Test URLs:
https://loggedin-checkout--boilerplate-commerce-dropins--hlxsites.hlx.page/
https://loggedin-checkout--boilerplate-commerce-dropins--hlxsites.hlx.page/cart
https://loggedin-checkout--boilerplate-commerce-dropins--hlxsites.hlx.page/checkout
https://loggedin-checkout--boilerplate-commerce-dropins--hlxsites.hlx.page/order-confirmation?orderRef=abc
https://loggedin-checkout--boilerplate-commerce-dropins--hlxsites.hlx.page/products/crown-summit-backpack/24-MB03

2024-05-30 17:47 UTC, sirugh commented
After #54 is merged, would you please rebase and validate again :)

2024-06-06 15:24 UTC, fnhipster requested changes

2024-06-06 15:24 UTC, fnhipster commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
Do we need to initialize **Checkout** and **Order Confirmation** on the top level? The bundles will be downloaded and initialized on every page, including PDP and Content. These should be in their corresponding Blocks (see PDP, for example).

Note: Cart and Auth are only initialized globally because they are used on multiple pages, i.e., Mini Cart.

2024-06-06 15:39 UTC, emipallares commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
@fnhipster Would you move the `authenticated` event listener to the corresponding block as well? We need to set headers when authentication changes, and we are doing that for all required dropins in the **dropins.js** file.

2024-06-06 15:40 UTC, herzog31 commented on blocks/modal/modal.js
> +// This is not a traditional block, so there is no decorate function. Instead, links to
If this is not a block, it's probably better to move it to the `scripts` folder.

2024-06-06 15:40 UTC, herzog31 commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
+1

2024-06-06 15:51 UTC, fnhipster commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
@emipallares, it would be better to move that logic to their corresponding blocks. 

Is there a way we can abstract it into a reusable function across multiple blocks?

2024-06-06 15:51 UTC, emipallares commented on blocks/modal/modal.js
> +// This is not a traditional block, so there is no decorate function. Instead, links to
@herzog31 This is a copy/paste from the Modal of the Block Collection available here: https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/edge-delivery/build/block-collection.

Would you still move it to the `scripts` folder?

2024-06-06 15:55 UTC, emipallares commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
@fnhipster Let's try that. Would you create this abstraction in the `scripts` folder?

2024-06-06 16:44 UTC, emipallares commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
@fnhipster please have a look at the implementation I did in this commit with the abstraction to setup the api authentication header: https://github.com/hlxsites/boilerplate-commerce-dropins/pull/49/commits/dc79a5b6c75f428cd8382a7280dc3b4deb0e5d50

2024-06-06 16:52 UTC, herzog31 commented on blocks/modal/modal.js
> +// This is not a traditional block, so there is no decorate function. Instead, links to
Got it. Could you please add the script.js part as well? https://experienceleague.adobe.com/en/docs/experience-manager-edge-delivery/using/other/developer/modal#:~:text=copy%20the%20autoLinkModals()%20function%20and%20add%20to%20your%20scripts.js%20file

2024-06-06 17:01 UTC, emipallares commented on blocks/modal/modal.js
> +// This is not a traditional block, so there is no decorate function. Instead, links to
@herzog31 Sure, I added the missing script part here: https://github.com/hlxsites/boilerplate-commerce-dropins/pull/49/commits/70053bbffc879068b7107b3cb12ceff7e8e48fd7

2024-06-06 22:25 UTC, fnhipster commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
@emipallares, **Auth**, **Cart**, **Checkout**, and **Order Confirmation** use the same endpoint (core) that gets set once on `dropins.js.` The unique instance is on PDP since it uses a different endpoint URL, which is not even required since PDP doesn't have an authenticated state.

 By utilizing the `setHeader` function from the global instance (`@adobe/fetch-graphql`), you can efficiently set the headers just once. This approach ensures that the headers are applied to all dropins using core, eliminating the need to set them individually on each dropin. 

You should be able to simplify your implementation by setting all headers in `dropins.js` using the global instance from `import { setFetchGraphQlHeader } from @dropins/tools/fetch-graphql.js`

2024-06-07 05:30 UTC, dpatil-magento commented
@emipallares Could not test on CI deployed url because of CORS issues, but overall local testing looks good.  One observation ( Not sure if I called it before )- on order confirmation when user sign-out then still order info is displayed.

2024-06-07 11:02 UTC, emipallares commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
@fnhipster I did not know these functions existed, so I updated the code to use `setFetchGraphQlHeader` and `removeFetchGraphQlHeader`. Please, check this commit: https://github.com/hlxsites/boilerplate-commerce-dropins/pull/49/commits/d44fbcd2f2e12686d86fc43ba55e7b63e393f593

2024-06-07 11:05 UTC, emipallares commented
> @emipallares Could not test on CI deployed url because of CORS issues, but overall local testing looks good. One observation ( Not sure if I called it before )- on order confirmation when user sign-out then still order info is displayed.

@dpatil-magento, thanks for taking a look and catching that. I'll open a ticket so we can address that scenario.

2024-06-07 12:22 UTC, fnhipster commented on scripts/dropins.js
> +  initializers.register(orderConfirmationApi.initialize, {});
Looks great! Thanks @emipallares

2024-06-07 12:22 UTC, fnhipster approved these changes

2024-06-07 12:23 UTC, fnhipster commented
LGTM! 👍

2024-06-07 12:46 UTC, herzog31 approved these changes

2024-06-10 08:36 UTC, emipallares commented
> @emipallares Sorry if my comment added confusion, but PR should always work on .page, .live just like main branch. I did smoke test on integration to uncover any bugs as could not test on .page/.live

We are waiting for a new release of the Cart drop-in to avoid CORS issue so we can make this PR work on .page and .live.

2024-06-12 12:48 UTC, dpatil-magento commented
QA Approved

2024-06-12 14:06 UTC, merged