Handle QA feedback provided
hlxsites/boilerplate-commerce-dropins pull request #56
Opened 2024-06-03 21:37 UTC by KostiantynFandeliuk

**Bug fixes identified by QA**

- Internal task number - USF-1281
- External task number - EDS-232

1. Reset password URL has user email in it. Not big deal but I have not seen this in any other websites while password reset. (Dont remember, but i provided this feedback some where, please ignore if this is already discussed).
2. Combined Auth Modal overlay does not close on hitting Esc key.
3. Even after login, Combined Auth header button still there.
4. Cart, Checkout, PDP does load well in Mobile device but Combined Auth Modal overalys, SignIn Underlay, My account Underlay, SignIn text, My account page after login does not look good in mobile device.

Test URLs:
https://fixed-bug-boilerplate-integration-auth-dropin--boilerplate-commerce-dropins--hlxsites.hlx.live/customer/login

2024-06-04 08:17 UTC, KostiantynFandeliuk commented
@sirugh Could you do a code review for me, please? Thank you.

2024-06-04 14:55 UTC, fnhipster requested changes

2024-06-04 14:55 UTC, fnhipster commented on blocks/header/renderAuthDropdown.js
> +      }),
Are these meant to be "slots"? If so, we need to use the Slot API instead for consistency. For example, [here is how PDP implement slots like "Title" ](https://git.corp.adobe.com/magento-datalake/storefront-pdp/blob/d4857537f19d658d813d078c12727b6a1db9a573/src/containers/ProductDetails/ProductDetails.tsx#L309)

Storefront (boilerplate) Implementation would look something like

```js
slots: {
  successNotificationForm: (ctx) => {
  // root elem
   const elem = document.createElement('div');

   // renders container
    const container = authRenderer.render(SuccessNotification, {
        ...
        messageText: ctx.dictionary.Auth.SuccessNotification.message,
        ...
    })(elem);

    // adds container into slot
    ctx.appendChild(elem);
  }
```

By using Slots, the developer can leverage data from the `context` including locale dictionary and lifecycle.

2024-06-14 19:30 UTC, fnhipster commented on blocks/header/renderAuthDropdown.js
> +      }),
After reviewing further, these might not be actual `slots` and the problem might be a misalignment on the demo implementation in the boilerplate. Let's ignore my comment above and perhaps revisit on the Boilerplate instead.

2024-06-14 19:31 UTC, fnhipster approved these changes

2024-06-14 19:51 UTC, KostiantynFandeliuk commented on blocks/header/renderAuthDropdown.js
> +      }),
Thank you for your response. I will finish the implementation requested by @sirugh  and make an additional push to this PR. (refactor Dropdown)

2024-06-14 22:01 UTC, KostiantynFandeliuk commented
**Example after refactor**

https://github.com/hlxsites/boilerplate-commerce-dropins/assets/85105163/10abe531-ca89-405c-baf8-f49688827c48

https://github.com/hlxsites/boilerplate-commerce-dropins/assets/85105163/bfc932d9-7c97-4416-9d81-06f946cb977a

@sirugh could you check please ? Thank you.

2024-06-18 13:46 UTC, sirugh commented
If i click sign in first then the search, sometimes the search shows up and sign in goes away, and sometimes search shows up behind sign in. When search does show up behind sign in, I cant close the sign in modal. To repro, you can just click and open and close sign in and search modal a few times from the top right buttons.

2024-06-18 14:16 UTC, sirugh commented on blocks/header/header.js
> +  const expanded =
Please fix this.

2024-06-18 14:42 UTC, KostiantynFandeliuk commented on blocks/header/header.js
> +  const expanded =
Fixed

2024-06-18 16:08 UTC, sirugh approved these changes

2024-06-18 16:52 UTC, merged