Integrate ReCaptcha module in boilerplate
hlxsites/boilerplate-commerce-dropins pull request #67
Opened 2024-07-17 11:42 UTC by KostiantynFandeliuk

**Added recaptcha config**

Acceptance criteria
1. Auth drop-in version updated to 0.0.1-alpha6 in boilerplate environment.
2. Auth Drop-In functionality tested in boilerplate environment locally, with our local backend.
3. Auth Drop-In functionality tested in boilerplate environment on EDS-deployed page (with boilerplate PR).
4. Auth Drop-In functionality on checkout and order confirmation pages tested in boilerplate environment on EDS-deployed page (with boilerplate PR). Notice, that order confirmation page for guest user is broken. Use signed-in user for tests.

Test URLs:
Before: https://main--boilerplate-commerce-dropins--hlxsites.hlx.live/
After: https://integrate-recaptcha--boilerplate-commerce-dropins--hlxsites.hlx.live/

2024-07-18 09:50 UTC, Ferri0 approved these changes

2024-07-18 15:05 UTC, fnhipster requested changes

2024-07-18 15:05 UTC, fnhipster commented on scripts/dropins.js
> +  recaptcha.setEndpoint(await getConfigValue('commerce-core-endpoint'));
I don't believe this line is needed since `recaptcha` is using core which is already globally set in the line above. Can you confirm?

You would only need/want to set the module or dropin endpoint again if the endpoint is different to core/global or you need/want to detach the instance to use its own headers detached to the global instance.

2024-07-18 16:32 UTC, fnhipster approved these changes

2024-07-18 20:56 UTC, dpatil-magento commented
@KostiantynFandeliuk Please check following - 
1. When Admin is not configured for recaptcha then there is console error logged regarding  missing config. not sure iif its needed.
2. Auth overlay on checkout page (invoked via sign in link in address form) - recaptcha does not show up for first time on sign in, sign up, forgot password forms.

2024-07-23 16:08 UTC, Ferri0 commented
@dpatil-magento Please, take a look at this PR once more when you will have a chance 🙏 
We've fixed reported issues and included latest version of auth drop-in.

2024-07-23 19:43 UTC, dpatil-magento commented
QA Approved.

2024-07-23 19:43 UTC, merged